### ISSUE TITLE
RSS guid is new for each build

### ISSUE THREAD

**Issue by dobladov** [vickOnRails/next-starter-peacock#10]
**Describe the bug**
It seems that every time a build is produced it generates new guid for the rss feed causing all articles to be show as new articles.

**To Reproduce**
Add the site to an RSS reader (inoreader in my case)
Read all articles, wait for new articles or a new build
All articles appear as unread

**Expected behavior**
Only new articles have a new guid

**Screenshots**
<img width="991" alt="Screenshot 2021-05-10 at 20 00 35" src="https://user-images.githubusercontent.com/1938043/117703841-7470ed00-b1ca-11eb-9a61-b93b4b5b7f6a.png">
(All have the same update time)

**Comment by vickOnRails** [comment]
Oh boy 😂

This is soo funny. Thanks a lot for pointing out.

I'll investigate and see how I can fix this. Thanks again Man.

**Comment by vickOnRails** [comment]
Hello there @dobladov. I tried to replicate this with [feedly](http://feedly.com/) but I couldn't find the issue you mentioned. Maybe it was from your RSS reader? Which one did you use specifically?

![screencapture-feedly-i-subscription-feed-https-victorofoegbu-com-rss-xml-2021-06-04-10_21_46](https://user-images.githubusercontent.com/24235881/120779192-bfa6c300-c51e-11eb-9e74-3b10ae19f885.png)

**Comment by dobladov** [comment]
I used [Inoreader](https://www.inoreader.com), this only happens with your blog, unfortunately.

It would be perfect if you use the url of the post for the guid since it should not change between builds, I love to read your blog but is really annoying to get all the old posts each time you post something new 😅

**Comment by vickOnRails** [comment]
Okay great. Thanks for the reply. I'll test with Inoreader and get back to you.

Thanks again.

**Comment by dobladov** [comment]
My guess is that it should be fixed if instead of the content id (which would change with each build) you pass here the url. 

https://github.com/vickOnRails/next-starter-peacock/blob/c9f8e6a1af08ac14882796aaaf1092fa9fec8166/lib/rss.ts#L41 and https://github.com/vickOnRails/next-starter-peacock/blob/c9f8e6a1af08ac14882796aaaf1092fa9fec8166/lib/rss.ts#L55

**Comment by vickOnRails** [comment]
🤦🏼‍♂️

The `id` was actually regenerated on each build. I thought I was using the `url` renamed to `id`. 

https://github.com/vickOnRails/next-starter-peacock/blob/c9f8e6a1af08ac14882796aaaf1092fa9fec8166/lib/rss.ts#L32-L58

This is where the `id` for each post is generated

https://github.com/vickOnRails/next-starter-peacock/blob/c9f8e6a1af08ac14882796aaaf1092fa9fec8166/lib/content.ts#L155-L170

Hopefully, this fixes it. Phew!
