### ISSUE TITLE
Upgrade to nextjs 13's new app router

### ISSUE THREAD

**Issue by vickonrails** [vickonrails/next-starter-peacock#15]
**Is your feature request related to a problem? Please describe.**
There's currently a lot of duplicated code for different types of page layouts. It would be nice to take advantage of the new and shiny features in Nextjs 13.2 (App router and react server components). 

**Describe the solution you'd like**
Migrate the whole code to the new app router, so it can also implement server components.

**Comment by vickonrails** [comment]
Hi there @karlhorky, I spent some time working on this and I'd say it's almost done rn. The thing I need to verify is the static pregeneration generation. I remember this wasn't working 100%. 

But I can look at it later today. But this shouldn't be a problem as the live site is hosted [here](https://next-starter-peacock.vercel.app/). 

Do you need this rn?

**Comment by karlhorky** [comment]
No rush on it, definitely!

Thanks for your continued hard work here! ❤️

**Comment by vickonrails** [comment]
No problems @karlhorky, glad it was useful to you ♥️

**Comment by karlhorky** [comment]
@vickonrails Oh great, is the migration to the App Router complete now that PR #19 was merged? 🙌  I'll give it a shot!
